### ISSUE TITLE
server table name

### ISSUE THREAD

**Issue by eni9mv** [Summer-16/CSGO-VMPanel#21]
Hi ...
i have a problem
i dont understand why!!! when i add the server on VMPanel it shows me this message: 
Server/table not found, Please add vmpanel plugin in your server then add here., Please try again

and the plugin is working on my server called: "SM VMPanel " (2.1 beta) by Summer Soldier

what i have to add here > sm_vmpServerTable "sv_table" !!
which table u are talking !!
Thanks!!

**Comment by eni9mv** [comment]
plugin on my databases.cfg 
	"sv_table"
	{
		"driver"			"sv_table"
		"host"				"localhost"
		"database"			"testvdb"
		"user"				"test"
		"pass"				"test"
		//"timeout"			"0"
		"port"			"3306"
	}

**Comment by skyycodes** [comment]
Use same table name from your config file (cfg/sourcemod/VMPanel.cfg)

**Comment by eni9mv** [comment]
> Use same table name from your config file (cfg/sourcemod/VMPanel.cfg)

i dont understand exactly .... give me example

**Comment by eni9mv** [comment]
Solved

**Comment by Summer-16** [comment]
Just for information if anyone else comes here again.
sm_vmpServerTable in plugin's CFG is the name of the table which will be created in the database by the plugin on 1st run, and then used further by panel and plugin for VIP entries (so while setting up the plugin you just need to give a friendly name for your servers like awp_server or  bhop_server_1)
then 
after that while adding the server in the panel just enter that same name in the table name and you are good to go.
