### ISSUE TITLE
I need help please 

### ISSUE THREAD

**Issue by eni9mv** [Summer-16/CSGO-VMPanel#23]
how can i use the payment only with paypal not with PayU

**Comment by Summer-16** [comment]
To use only PayPal and disable PayUmoney use the following gateway configuration in your config file, where you add your PayPal client id only
And update the current in your panel setting and for servers to USD 

----------

  "payment_gateways": {
    "paypal": {
      "paypal_client_id": "Your paypal client id here for live environment "
    },
    "payU": {
      "enabled": false,
      "environment": "test",
      "merchantKey": "" ,
      "merchantSalt": "" 
    }
  },

**Comment by Summer-16** [comment]
Resolved
