### ISSUE TITLE
Problem behind problem ... on this tutorial

### ISSUE THREAD

**Issue by eni9mv** [Summer-16/CSGO-VMPanel#24]
i surrender... my brain is dead, i stay on my computer a whole time ..
everytime facing problems on this panel i very waste my time ...sorry
*****
problem:
Server/table not found, Please add vmpanel plugin in your server then add here., Please try again
*****
i did all what u said and what u told me... so i think there is something fake here .... i don't know the tutorial is bad ....

**Comment by Summer-16** [comment]
There is nothing fake here, its just new for people's in Esports Community bcoz they all are become so used to the concept of spoon feeding.
Anyway i will try my best to resolve your issue as always 
Provide me following information 

- Panel version
- Plugin version
- Database cfg entry in server
- make sure you are using the same db credentials for plugin and panel
- any errors thrown by plugin in server console

**Comment by eni9mv** [comment]
yes there is 4 errors in plugin :(

**Comment by Summer-16** [comment]
That's why it is not working, as mentioned in instructions, you or plugin can only add server in panel once plugin starts working without any errors.
So you should fix those errors to make it work and If you can provide some logs about those errors from sourcemod then i can also help

**Comment by eni9mv** [comment]
i will try to install it from 0, if i got any solution i will tell u

**Comment by eni9mv** [comment]
sm_vipRefresh
***[VMP] Executing manual refresh triggered by command
***[VMP] Requesting user is an Admin/Console, Executing the command
L 12/07/2020 - 19:55:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/07/2020 - 19:55:05: [SM] Blaming: vmpanel.smx
L 12/07/2020 - 19:55:05: [SM] Call stack trace:
L 12/07/2020 - 19:55:05: [SM]   [0] Database.Query
L 12/07/2020 - 19:55:05: [SM]   [1] Line 96, C:\TestServer\csgoserver\csgo\addons\sourcemod\scripting\vmpanel.sp::refreshVipAndAdmins
L 12/07/2020 - 19:55:05: [SM]   [2] Line 145, C:\TestServer\csgoserver\csgo\addons\sourcemod\scripting\vmpanel.sp::handler_RefreshVipAndAdmins

**Comment by Summer-16** [comment]
that is a simple MySQL connection error, Restarting the server should solve it

**Comment by eni9mv** [comment]
same thing and... Server/table not found, Please add VM-Panel plugin in your server then add here., Please try again
i dont understand whats happening i add the database on phpmyadmin i did everything correctly... so whats the problem ??
should i run shell_script ?? if yes so how ?

**Comment by eni9mv** [comment]
when i go to the panel-> Audit Logs i can see this 

Manual Refresh Executed | Old VIPs and deleted and new data is updated in servers | admin | 2020-12-08T18:39:08.000Z

but the server is not added in the panel ...

**Comment by Summer-16** [comment]
> same thing and... Server/table not found, Please add VM-Panel plugin in your server then add here., Please try again
> i dont understand whats happening i add the database on phpmyadmin i did everything correctly... so whats the problem ??
> should i run shell_script ?? if yes so how ?

---------------------------------------------

U can keep blaming the stuff all day long and it will not help anyone, i already asked you to provide me details and logs if want to get real help.
and just for the record with plugin v2.1.1 there is no need to add server in panel (Plugin adds the server in panel automatically)

**Comment by eni9mv** [comment]
i can give u my VPS and setup this thing for me !!!

**Comment by Summer-16** [comment]
> i can give u my VPS and setup this thing for me !!!

----------------------

For that, you can get in touch with me in discord. 

but somehow I have a feeling that you are setting up the plugin in the wrong way and that's where your errors are.

**Comment by Summer-16** [comment]
No response from user, Closing for now. Please, reopen if help required.
