### ISSUE TITLE
Discord Error

### ISSUE THREAD

**Issue by shaikhnedab** [Summer-16/CSGO-VMPanel#3]
getting following error when script tries to cron run sendDisordMesaage.
```
Cron running-->
error in sendMessageOnDiscord-> TypeError: Cannot read property 'toUpperCase' of undefined    at /home/vipsystem/panelServer/app/controllers/sendMessageOnDiscord.js:31:62
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Unhandled Rejection at: TypeError: Cannot read property 'toUpperCase' of undefined
    at /home/vipsystem/panelServer/app/controllers/sendMessageOnDiscord.js:31:62
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Also what is Admin List?

**Comment by Summer-16** [comment]
I think u upgraded to under development code my friend.

**Comment by Summer-16** [comment]
you should stick to the version releases, but don't worry v1.2 is coming this week.

**Comment by Summer-16** [comment]
Code is almost ready but I am not releasing the next version I need some time to testings.
But as you happen to update into a dev version please use the latest code and your errors should be fixed.
And please update your config from example.

**Comment by shaikhnedab** [comment]
thanks for updating it. i will test it soon
