### ISSUE TITLE
``node server.js`` error

### ISSUE THREAD

**Issue by cutehosting** [Summer-16/CSGO-VMPanel#33]
Dear Coder, 
I have followed you wili but at the step ``node server.js`` this happens.
![image](https://user-images.githubusercontent.com/80317979/110445495-75987780-80be-11eb-8bf1-64b87bd94fd2.png)

I am using Centos 7  and Node.js v10.23.1

**Comment by cutehosting** [comment]
Hi, i have fixed it by changing the password but now i got this error
![image](https://user-images.githubusercontent.com/80317979/110447558-a2e62500-80c0-11eb-908a-13956dd8eed5.png)

**Comment by skyycodes** [comment]
Hey,
You have to install log4js 
To install it, type npm install log4js in console

**Comment by cutehosting** [comment]
Thank you, i saw that...Now i got this error.
![image](https://user-images.githubusercontent.com/80317979/110455117-53a3f280-80c8-11eb-8d0a-cb344a0bb068.png)

**Comment by cutehosting** [comment]
Before it was working

**Comment by cutehosting** [comment]
fixed. The problem now is this "Server/table not found, Please add vmpanel plugin in your server then add here., Please try again"
![image](https://user-images.githubusercontent.com/80317979/110461591-edbb6900-80cf-11eb-923d-7da657ad56ca.png)
![image](https://user-images.githubusercontent.com/80317979/110461629-f90e9480-80cf-11eb-89da-5b3c1ead817b.png)

**Comment by cutehosting** [comment]
![image](https://user-images.githubusercontent.com/80317979/110463255-fad95780-80d1-11eb-88ff-e4bf85170444.png)
seems that there is not table

**Comment by shaikhnedab** [comment]
have you followed plugin installation guide?
https://github.com/Summer-16/CSGO-VMPanel#install-plugin-in-csgo-server

**Comment by cutehosting** [comment]
yep 
![image](https://user-images.githubusercontent.com/80317979/110468673-e2b90680-80d8-11eb-8c16-026644731da2.png)
i have just done this. I have used mariadb so maybe is this the problem. What should i write as driver?
Thank you

**Comment by Summer-16** [comment]
This server setup issue was resolved on Discord.
