### ISSUE TITLE
Can't connect to SQL server.

### ISSUE THREAD

**Issue by Playstationset** [Summer-16/CSGO-VMPanel#40]
***[VMP] Database connection is null in , Making a new Connection Now
***[VMP] Making a Database Connection
***[VMP] SQL Connection created succesfully
***[VMP] Can't connect to SQL server. Error: Could not find driver "mysql"
L 06/27/2021 - 10:58:38: [vmpanel.smx] [VMP] Can't connect to SQL server. Error: Could not find driver "mysql"

Can't connect, what's the problem? I googled it and they said that pdo_mysql was not installed. Is this problem caused?

**Comment by TandelK** [comment]
Basically your system does not have compatible system requirements to allow mysql extension of sourcemod to run.

**Comment by Playstationset** [comment]
> 基本上你的系统没有兼容的程序来允许 sourcemod 的 mysql 扩展运行。

But I have followed the steps on the page and installed it step by step, including Mysql 5.7 and Node.js 14

**Comment by Playstationset** [comment]
I have searched a lot about "error: could not find driver "mysql"", but I still found nothing.

**Comment by Playstationset** [comment]
Solution for CentOS
HTML Code:

yum install zlib.i686
