### ISSUE TITLE
Enhancement ideas for better version.

### ISSUE THREAD

**Issue by nguyenbaodanh** [Summer-16/CSGO-VMPanel#5]
- users can login via steam to buy VIP or check days left for renewal if they want.
- integrate with sourcebans++ ( including admin groups, flags, server groups, etc...)
- automatic vip/admin payment through pay gates like Paypal, skrill and more (including automatic monthly renew)
    + users can choose server groups to register for VIP/Admin subscribe
    + or users can choose single server to subscribe
- vip/admin listing/manage for each server/subscribe package (oh wait you already got this!)
- VIP/ admins add/expire log?
- Users expire / days left alert?
- log server kick/ban/gag/mute for admins
- coupon codes / discount codes ?
- Servers remote console for admins?

I'm using [Donation control ](https://forums.alliedmods.net/showthread.php?t=221742&highlight=sourcebans), maybe you can take a look and make your more powerful.
Here is mine [VIP reg through Paypal page](http://vip.1hp-gaming.com/) by Donation control

**Comment by Summer-16** [comment]
#4
