### ISSUE TITLE
Configuration "vmpanel" not found

### ISSUE THREAD

**Issue by henriquemod** [Summer-16/CSGO-VMPanel#7]
Im getting this error, could you help me?

] rcon sm_vmprefresh
***[VMP] Executing manual refresh on user command***
***[VMP] Error connecting to database==> Configuration "vmpanel" not found
L 06/03/2020 - 00:06:39: [vmpanel.smx] ***[VMP] Error connecting to database==> Configuration "vmpanel" not found
***[VMP] Reloading Admins in server Now***
L 06/03/2020 - 00:06:39: [basecommands.smx] "Console<0><Console><Console>" refreshed the admin cache.
[SM] Admin cache has been refreshed.

**Comment by Summer-16** [comment]
Looks like you forgot to add vmpanel database object, in your server's database cfg for vmpanel plugin

**Comment by henriquemod** [comment]
> Looks like you forgot to add vmpanel database object, in your server's database cfg for vmpanel plugin

Indeed, after adding the vmpanel entry on database.cfg it was able to connect, however i got another error. The plugin automatic created the db "teste" that i specified in config.json, it even created 4 tables, but when e try to run sv_prefresh it gives me that error:

sm_vmprefresh
***[VMP] Executing manual refresh on user command***
***[VMP] Running query to fetch vip and admins***
***[VMP] Error in fetching vip and admin list (error: Table 'teste.sv_table' doesn't exist)
L 06/03/2020 - 21:08:37: [vmpanel.smx] ***[VMP] Error in fetching vip and admin list (error: Table 'teste.sv_table' doesn't exist)

I let the sv_table default on VMPanel.cfg, its interesting that it had created 4 tables but not this one, did i miss something?

**Comment by Summer-16** [comment]
Those 4 tables were created by the panel server,
sv_table or whatever mentioned in plugin config will be created by the plugin, and for doing that it will require connection with MySQL.
So after adding the proper database.cfg entry for vmpanel restart the server and plugin should create your server table.

**Comment by Summer-16** [comment]
resolved
